#!/bin/sh

#Define the variable to find a random wallpaper
random_wallpaper=$(find ~/Documents/rice/dotfiles/wallpapers -type f -iname '*.jpg' -o -iname '*.png' | shuf -n 1)

#Set wallpaper
gsettings set org.gnome.desktop.background picture-uri-dark "file://$random_wallpaper"

wal -c

#Set color scheme for terminal
wal -i "$random_wallpaper"

#Set color scheme for firefox browser
pywalfox update

